services:
  habbo-origins-dcr:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: habbo-origins-dcr
    ports:
      - "8080:80"
    volumes:
      - ./src/data:/var/www/html
    environment:
      - AWS_BUCKET=
      - AWS_ENDPOINT=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
